server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:bitebazaar;DB_CLOSE_DELAY=-1
    username: sa
    password:

security:
  jwt:
    secret: change-me-please-32-chars
    expires-in-min: 60